AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('App.urls', namespace='axf')),
]

App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^market/(\d+)/(\d+)/(\d+)/', views.market, name='market'),
    url(r'^user/', views.user, name='user'),
    url(r'^checkaccount/', views.checkAccount, name='checkaccount'),
    url(r'^createaccount/', views.createAccount, name='createaccount'),
    url(r'^login/', views.login, name='login'),
    url(r'^dologin/', views.doLogin, name='dologin'),
]

templates/App/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"/>
    <link rel="stylesheet" href="{% static 'base/css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">


    <script type="text/javascript" src="{% static 'base/js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'base/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'base/js/swiper.js' %}"></script>
    <script type="text/javascript" src="{% static 'base/js/base.js' %}"></script>

    <title></title>
    {% block personResource %}{% endblock %}
    <style>
        header {
            font-size: 20px;
            text-align: center;
            line-height: 1.5rem;
        }
    </style>
</head>
<body>
<header>{{ pagetitle }}</header>
<div>
    {% block content %}

    {% endblock %}
</div>
<footer>
    <a href="{% url 'axf:home' %}" class="home">
        <dl>
            <dt><span></span></dt>
            <dd>首页</dd>
        </dl>
    </a>
    <a href="/axf/market/104749/0/0" class="market">
        <dl>
            <dt><span></span></dt>
            <dd>闪购</dd>
        </dl>
    </a>
    <a href="{% url 'axf:cart' %}" class="cart">
        <dl>
            <dt><span></span></dt>
            <dd>购物车</dd>
        </dl>
    </a>
    <a href="{% url 'axf:user' %}" class="mine">
        <dl>
            <dt><span></span></dt>
            <dd>我的</dd>
        </dl>
    </a>
</footer>
</body>
</html>

templates/App/cart.html
{% extends 'App/base.html' %}
{% load static %}

{% block personResource %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">
{% endblock %}

templates/App/home.html
{% extends 'App/base.html' %}
{% load static %}

{% block personResource %}
    <link rel="stylesheet" href="{% static 'home/css/home.css' %}">
    <script type="text/javascript" src="{% static 'home/js/home.js' %}"></script>
{% endblock %}



{% block content %}
    <div id="home">

        <div class="swiper-container" id="topSwiper">
            <div class="swiper-wrapper">
                {% for wheel in wheelList %}
                    <div class="swiper-slide"><img src="{{ wheel.img }}"></div>
                {% endfor %}
            </div>
            <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullet"></div>
        </div>

{#        <div id="topMenu">#}
{#                {% for nav in navList %}#}
{#                    <a href="">#}
{#                        <div class="nav">#}
{#                            <img src="{{ nav.img }}">#}
{#                            <span>{{ nav.name }}</span>#}
{#                        </div>#}
{#                    </a>#}
{#                {% endfor %}#}
{#        </div>#}

        <section class="topMenu">
        <nav>
            <ul>
                {% for item in navList %}
                <li>
                    <a href="#">
                        <img src="{{item.img}}" />
                        <span>{{item.name}}</span>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </nav>

        <menu class="swiper-container swiperMenu" id="swiperMenu">
            <ul class="swiper-wrapper">
                {% for item in buyList %}
                <li class="swiper-slide">
                    <a><img src="{{item.img}}"/></a>
                </li>
                {% endfor %}
            </ul>
        </menu>

    </section>

    <section class="CVS">
        <h2>
            <img src="{{shop1.img}}" alt="{{shop1.name}}"/>
        </h2>

        <fieldset>
            {% for x in shop2 %}
                <a href="#">
                    <img src="{{x.img}}" alt="{{x.name}}"/>
                </a>
            {% endfor %}
        </fieldset>

        <ul>
            {% for x in shop3 %}
                <li>
                    <a href="#">
                        <img src="{{x.img}}" />
                        <span>{{x.name}}</span>
                    </a>
                </li>
            {% endfor %}
        </ul>

        <ol>
            {% for x in shop4 %}
                <li><a href="#"><img src="{{x.img}}" alt="{{x.name}}"/></a></li>
            {% endfor %}
        </ol>
    </section>




    <section class="mainInfo">
        {% for item in mainList%}
            <section>
                <h3>
                    {{item.name}}
                    <a ui-sref="#">更多></a>
                    <span></span>
                </h3>
                <div>
                    <a href="#"><img src="{{item.img}}" alt="item.name"/></a>
                </div>
                <ul>
                    <li>
                        <a href="#">
                            <img src="{{item.img1}}"/>
                            <span class="description">{{item.longname1}}</span>
                            <span>¥{{item.price1}}</span>
                            <s>¥{{item.marketprice1}}</s>
                        </a>
                        <button><span>&#43;</span></button>
                    </li>
                    <li>
                        <a href="#">
                            <img src="{{item.img2}}"/>
                            <span class="description">{{item.longname2}}</span>
                            <span>¥{{item.price2}}</span>
                            <s>¥{{item.marketprice2}}</s>
                        </a>
                        <button><span>&#43;</span></button>
                    </li>
                    <li>
                        <a href="#">
                            <img src="{{item.img3}}"/>
                            <span class="description">{{item.longname3}}</span>
                            <span>¥{{item.price3}}</span>
                            <s>¥{{item.marketprice3}}</s>
                        </a>
                        <button><span>&#43;</span></button>
                    </li>
                </ul>
            </section>
        {% endfor %}
    </section>

    </div>
{% endblock %}

templates/App/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"/>
    <link rel="stylesheet" href="{% static 'base/css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'mine/css/user.css' %}">


    <script type="text/javascript" src="{% static 'base/js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'base/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'base/js/swiper.js' %}"></script>
    <script type="text/javascript" src="{% static 'base/js/base.js' %}"></script>
{#    <script type="text/javascript" src="{% static 'mine/js/user.js' %}"></script>#}

    <title></title>
    <style>
        #back {
            line-height: 1.5rem;
            margin-left: 0.3rem;
            font-size: 16px;
        }
    </style>
</head>
<body>
<header><a href="{% url 'axf:home' %}"><span id='back' class="glyphicon glyphicon-menu-left"
                                             aria-hidden="true"></span></a></header>

<form id="userBox" action="{% url 'axf:dologin' %}">
    <div class="userTheme"><input class="userData" id="userAccount" name="userAccount" type="text" placeholder="请输入用户名"><span id="status"></span><br /></div>
    <div class="userTheme"><input class="userData" id="userPassword" name="userPassword" type="password" placeholder="请输入密码"><br /></div>

    <div id="btnUser">
{#        <button id="btn" type="button" >注册</button><br />#}
        <button id="btn" type="submit" >登录</button>
    </div>
</form>

</body>

templates/App/market.html
{% extends 'App/base.html' %}
{% load static %}

{% block personResource %}
    <link rel="stylesheet" href="{% static 'market/css/market.css' %}">
    <script src="{% static 'market/js/market.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="market">
        <div class="aside">
            {% for foodType in foodTypes %}
                <span class="yellowLine"></span>
                <a href="{% url 'axf:market' foodType.typeid 0 0 %}">
                    <div class="typeFood">{{ foodType.typename }}</div>
                </a>

            {% endfor %}
        </div>

        <div class="nav">
            <div class="navSelect floatClear">
                <div class="leftChildType">全部类型<span class="glyphicon glyphicon-menu-down"
                                                     aria-hidden="true"></span></div>
                <div class="rightOrder">综合排序<span class="glyphicon glyphicon-menu-down"
                                                  aria-hidden="true"></span></div>
            </div>
            <div class="listBox">
                <span class="list"></span>
                <span class="list"></span>
            </div>
            <ul>
                {% for goods in goodsList %}
                    <li id="goodsList">
                        <div>
                            <img src="{{ goods.productimg }}">
                            <p>{{ goods.productname }}</p>
                            <p>{{ goods.price }}</p>
                            <button class="subShopping">-</button>
                            <num>{{ goods.num|default:0 }}</num>
                            <button class="addShopping">+</button>
                        </div>
                    </li>
                {% endfor %}
            </ul>


            <div id="typediv">
                <div>
                    {% for child in childType %}
                        <div>
                            <a id='btn'
                               href="{% url 'axf:market' foodType child.childType 0 %}"><span>{{ child.childName }}</span></a>
                        </div>
                    {% endfor %}
                </div>

            </div>

            <div id="sortdiv">
                <div>
                    <a href="" class="sort"><span>综合排序</span></a>
                    <a href="" class="sort"><span>销量排序</span></a>
                    <a href="{% url 'axf:market' foodType childcid 3 %}" class="sort"><span>价格最低</span></a>
                    <a href="{% url 'axf:market' foodType childcid 1 %}" class="sort"><span>价格最高</span></a>
                </div>
            </div>
        </div>


    </div>

{% endblock %}

templates/App/mine.html
{% extends 'App/base.html' %}
{% load static %}

{% block personResource %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}

{% block content %}
    <div id="mine">
        <section class="fixed">
{#            <span><img src="{{ account.userImg }}" id="userImg"></span>#}
            <span><img src="{{ account.userImg }}" id="userImg"></span>
{#            <span class="glyphicon glyphicon-user"></span>#}
            <p><a href="">{{ account.userAccount }}</a></p>
            <p><span class="glyphicon glyphicon-fire"></span><span>等级</span></p>
            <a id="regis" href="">注册</a>
            <p><span class="glyphicon glyphicon-heart"></span>商品收藏</p>
        </section>

        <section class="mine">
            <p>
                <span>我的订单</span><a>查看全部订单&gt;</a>
            </p>
            <nav id="nav">
                <ul>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-usd"></span></dt>
                                <dd>待付款</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-envelope"></span></dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-pencil"></span></dt>
                                <dd>待评价</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-retweet"></span></dt>
                                <dd>退款/售后</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </nav>


            <menu>
                <ul>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
                                <dd>积分商城</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-credit-card"></span></dt>
                                <dd>优惠券</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-import"></span></dt>
                                <dd>收货地址</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
                                <dd>客服/反馈</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-asterisk"></span></dt>
                                <dd>关于我们</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </menu>
            <p id="logout"><a href="{% url 'axf:login' %}">退出当前账号</a></p>
        </section>
    </div>
{% endblock %}

templates/App/user.html
{#{% load static %}#}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
    {#    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'base/css/swiper.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'base/css/bootstrap.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">#}
{##}
{#    <script type="text/javascript" src="{% static 'base/js/jquery.js' %}"></script>#}
{#    <script type="text/javascript" src="{% static 'base/js/bootstrap.js' %}"></script>#}
{#    <script type="text/javascript" src="{% static 'base/js/swiper.js' %}"></script>#}
{#    <script type="text/javascript" src="{% static 'base/js/base.js' %}"></script>#}
{##}
{#    <style>#}
{#        #back {#}
{#            line-height: 1.5rem;#}
{#            margin-left: 0.5rem;#}
{#            font-size: 30px;#}
{#        }#}
{##}
{#    </style>#}
{##}
{#    <title></title>#}
{#</head>#}
{#<body>#}
{#<header><a href=""><span id='back' class="glyphicon glyphicon-menu-left"#}
{#                                             aria-hidden="true">首页</span></a></header>#}
{##}
{#</body>#}
{#</html>#}